spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
    packages:
      trust-all: true
logging:
  config: classpath:log4j2.xml
mybatis:
  mapper-locations: classpath:src/main/java/com/zhihaoliang/demo/dao/base/mapping/*Mapper.xml
  type-aliases-package: com.zhihaoliang.demo.dao.base.dao
